AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'