version: '3'
services:
  db:
    container_name: blog_creator_api_db
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
  web:
    container_name: blog_creator_api_main
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/myapp
      - data-ruby-tmp:/myapp/tmp
      - data-ruby-bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  data-ruby-tmp:
    driver: local
  data-postgres:
    driver: local
  data-ruby-bundle:
    driver: local