---
- name: production deploy
  hosts: production
  remote_user: ubuntu
  vars:
    ansistrano_deploy_to: '/home/ubuntu/blog_creator_api'
    ansistrano_version_dir: 'releases'
    ansistrano_current_dir: 'current'
    ansistrano_keep_releases: 0
    ansistrano_deploy_via: 'git'
    ansistrano_allow_anonymous_stats: false
    ansistrano_git_repo: 'git@github.com:blog-creator-team/blog_creator_api.git'
    ansistrano_git_branch: 'master'
    ansistrano_git_identity_key_remote_path: '/home/ubuntu/.ssh/id_rsa'
    ansistrano_after_cleanup_tasks_file: '{{ playbook_dir }}/after_deploy.yml'
  roles:
    - role: ansistrano.deploy